development:
  adapter: postgresql
  host: localhost
  username: 
  password: 
  database: development
  encoding: UTF8

test:
  adapter: postgresql
  host: localhost
  username: 
  password: 
  database: test        # or whatever the name is
  encoding: UTF8